### ISSUE TITLE
ZeroBounce Email validation Automation using Engagement Studio

### ISSUE THREAD

**Issue by Danielagtr** [SalesforceLabs/EmailValidator#11]
Hi There, 

We have implemented the email validator app in Account Engagement and are trying to implement an Engagement Studio to automatically validate new leads ref: https://www.salesforceben.com/email-verification-tools-pardot/

We are unsuccesfull on this process and unable to automatically validate leads. Using the Zerobounce sourced extension via Salesforce is not an option as we only want to validate prospects in Account Engagement.

Does anybody have experience on this?

**Comment by cardax** [comment]
Hi @Danielagtr, 
happy to support!

Could you please provide more information about the issue?
What is unsuccessful? Could you share a screenshot of the logs?

**Comment by Danielagtr** [comment]
Hi there,

We created an Engagement Studio following the directions of the provided article:

***@***.***

But nothing happens and no emails get validated, its good to point out that we have been in contact with Salesforce directly and they have no governance of this app, Zerobounce is also not aware of how this works so at this point we are unsure on how to set up a monthly automated validation.


Best,

[NI]<https://www.ni.com/r/zf03uz>



Daniela Gutierrez
Senior Marketing Operations Analyst
Marketing Operations
ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL

**Comment by cardax** [comment]
That's correct, Salesforce Labs apps are created by Salesforce employees and are provided AS-IS and are not officially supported by Salesforce Support.

I'm one of the 2 developers of this extension.
Could you please confirm that you followed the **Setup Guide**? 
https://github.com/SalesforceLabs/EmailValidator/wiki/1.-Setup-Guide

You should see on Salesforce a list of log records that should allow us to figure out what the problem is: https://github.com/SalesforceLabs/EmailValidator/wiki/1.-Setup-Guide#7-troubleshooting

**Comment by Danielagtr** [comment]
Hi Giuseppe,

The Email Validation as been installed by our IT team and I confirmed that we have the latest available version.

I do see the Email Validator option when setting up the Engagement Studio, it just doesn’t run.

Step by step on how the Studio is programmed below:

This is the list we were initially using for testing; these prospects back then had no ZeroBounce status but have now been manually validated due to our inability to validate them automatically.

***@***.***


Check Email Step (Blurring BU Id)

***@***.***

External Activity:
***@***.***

Depending on that action we would add to a list:

***@***.***

I also want to point out that we created fields in our database to assign the corresponding ZeroBounce status fields:

***@***.***

We would like for the automation to run, validate, and then assign the results to these fields.

Best,

[NI]<https://www.ni.com/r/zf03uz>



Daniela Gutierrez
Senior Marketing Operations Analyst
Marketing Operations
ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL

**Comment by cardax** [comment]
Hi Daniela, thanks for your reply.
Would it be possible to ask your Salesforce Admin from IT to join the conversation here?
Without access to the logs, I'm afraid I won't be able to support.

Kind regards,
Giuseppe

**Comment by Danielagtr** [comment]
Hi Giuseppe,

Before I involve IT I would like to better understand who you work with and how this app exchange applications are set up, just before we disclose more information 😊 our Salesforce TAM was the one that guided me into your direction, do you guys work along Salesforce somehow?

Could you also confirm what kind of information will be needed from your end to figure this one out? We are very protective of our data so we want to better understand how this works.

Appreciate your help.

[NI]<https://www.ni.com/r/zf03uz>



Daniela Gutierrez
Senior Marketing Operations Analyst
Marketing Operations
ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL

**Comment by cardax** [comment]
Hi Daniela,
I'm a Technical Architect working at Salesforce Professional Services.
Your TAM should be able to confirm it / get in touch with me on the internal Slack.
This is just an employee-led project that we realized with another colleague in our free time and that we're open sourcing for free as part of the "Salesforce Labs" initiative (that's why it's not officially supported by Salesforce).

**Comment by Danielagtr** [comment]
Hi Giuseppe,

Thanks for the detail. I have included Ivannia in here, she was the one that installed the Email Validator.


Best

[NI]<https://www.ni.com/r/zf03uz>



Daniela Gutierrez
Senior Marketing Operations Analyst
Marketing Operations
ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL

**Comment by gcardaceSFDC** [comment]
Hi Daniela,
I cannot see your colleague Ivannia here in the GitHub conversation.
I think it would be better to continue the discussion via normal emails and maybe organize a quick Google Meet.
May I ask you to send me both your email addresses as Direct Message in the Salesforce Trailblazer Community?
You can message me from my profile page: https://www.salesforce.com/trailblazer/giuseppe

**Comment by Danielagtr** [comment]
Adding @Vollie ***@***.***>

Best regards,

[NI]<https://www.ni.com/r/zf03uz>



Ivannia Medina
Senior Engineer, CRM Platform
IT Infrastructure
+50625620024<tel:+50625620024>  |  ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL
From: Daniela Gutierrez ***@***.***>
Sent: Wednesday, January 10, 2024 8:39 AM
To: SalesforceLabs/EmailValidator ***@***.***>; SalesforceLabs/EmailValidator ***@***.***>
Cc: Mention ***@***.***>; Ivannia Medina ***@***.***>
Subject: RE: [SalesforceLabs/EmailValidator] ZeroBounce Email validation Automation using Engagement Studio (Issue #11)

Hi Giuseppe,

Thanks for the detail. I have included Ivannia in here, she was the one that installed the Email Validator.


Best

[NI]<https://www.ni.com/r/zf03uz>



Daniela Gutierrez
Senior Marketing Operations Analyst
Marketing Operations
ni.com<https://www.ni.com/>
[National Instruments is now NI.]




INTERNAL - NI CONFIDENTIAL

**Comment by gcardaceSFDC** [comment]
All email addresses here are masked (I cannot see them), you're writing on a publicly visible page.
Please write me privately via my profile: https://www.salesforce.com/trailblazer/giuseppe

I will delete this thread to hide the contact details and wait for your private message.
