### ISSUE TITLE
Pardot Authorization Error

### ISSUE THREAD

**Issue by jferree-entravision** [SalesforceLabs/EmailValidator#4]
Logs for Pardot show the following error

> Unable to complete the JWT token exchange. Error: invalid_grant. Error description: invalid assertion.

Instructions followed precisely.  Possibly an issue with Spring '23?

**Comment by gcardax-sfdx** [comment]
Hello, 
I would exclude issues with Spring '23 because it works today on a demo org we use for testing.
It must be an issue with the configuration of the Named Credential for Pardot.
Maybe we forgot a detail in the documentation.
Can you share a screenshot of your Pardot Named Credential (feel free to hide confidential info)?

**Comment by jferree-entravision** [comment]
Well that is good news at least. Here is my named credential.
![image](https://user-images.githubusercontent.com/124941679/218149690-c2e5bb40-049a-4dad-9373-f3cbe0c9e3ba.png)

**Comment by gcardax-sfdx** [comment]
Apologies for the late reply, did you install the package from AppExchange or just deployed the code from GitHub?
The screenshot seems correct to me, have you tried using the Named Credential in an Anonymous Apex to see if it works outside of our package?
For example, try running the following code in the developer console.
It should print out a list of all Lists in Pardot (replace the businessUnitId with your own):


```
// Define the named credential for Pardot API endpoint
String endpoint = 'callout:Email_Validator_Pardot/api/v5/objects/lists?fields=id,name&orderBy=id';
Id businessUnitId = 'REPLACE WITH YOUR BU ID';

// Create the HTTP request
HttpRequest request = new HttpRequest();
request.setHeader('Content-Type','application/json');
request.setHeader('Pardot-Business-Unit-Id', businessUnitId);
request.setEndpoint(endpoint);
request.setMethod('GET');
System.debug(request);

// Send the HTTP request using the named credential
Http http = new Http();
HTTPResponse response = http.send(request);

// Check the response status code
if (response.getStatusCode() == 200) {
    // Parse the JSON response to get the list names
    Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
    System.debug(result);
    
    List<Object> lists = (List<Object>) result.get('values');
    for (Object l : lists) {
        Map<String, Object> listData = (Map<String, Object>) l;
        String listName = (String) listData.get('name');
        System.debug('List Name: ' + listName);
    }
} else {
    System.debug('Error: ' + response.getStatusCode() + ' ' + response.getStatus());
}

```
