### ISSUE TITLE
Installation Error - Marketing App Extension

### ISSUE THREAD

**Issue by kxs2023** [SalesforceLabs/EmailValidator#6]
When installing this package the below error message appears. The selection for Install for Admins Only was chosen.

**Comment by kxs2023** [comment]
<img width="747" alt="image" src="https://github.com/SalesforceLabs/EmailValidator/assets/135356545/b5310bad-616b-43cd-b273-df257cc0ffde">

**Comment by gcardax-sfdx** [comment]
Hello,
thanks for your message!
Can you please confirm that your Account Engagement (Pardot org) is already set up with a Business Unit and that you have at least MCAE Plus edition?
I believe this feature is not available in Account Engagement Growth edition.
There are a few considerations when working with Marketing App Extensions: 
https://help.salesforce.com/s/articleView?id=sf.pardot_extensions_considerations.htm&type=5

**Comment by kxs2023** [comment]
Hi, the org I'm trying to install doesn't have Marketing App Extensions in the Marketing Setup which was the cause of the issue. Thanks!

**Comment by gcardax-sfdx** [comment]
Thanks for the confirmation, I've added the information about "Required Licenses" in the README and I'll update the documentation soon!

The Marketing App Extension features are only available in: 
**Account Engagement Plus, Advanced, and Premium Editions** 

https://help.salesforce.com/s/articleView?id=sf.pardot_extensions_considerations.htm&type=5
